# Generated by Django 3.2.8 on 2022-08-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=15, verbose_name='Cédula')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo electrónico')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('tipo', models.IntegerField(verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=15, verbose_name='Cédula')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo electrónico')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
            ],
        ),
    ]
